# Generated by Django 5.2.16 on 2026-07-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.PositiveIntegerField(help_text='En ajustes, la cantidad representa la existencia final contada.'),
        ),
    ]
