# Generated by Django 5.2.16 on 2026-07-22 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0007_sucursalempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('asunto', models.CharField(blank=True, max_length=160)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('pendiente', 'Pendiente'), ('respondido', 'Respondido'), ('cerrado', 'Cerrado')], default='nuevo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_contacto', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'mensaje de contacto',
                'verbose_name_plural': 'mensajes de contacto',
                'ordering': ['-fecha_creacion', '-id'],
                'indexes': [models.Index(fields=['empresa', 'estado', 'fecha_creacion'], name='contacto_me_empresa_bd6b0b_idx')],
            },
        ),
    ]
