# Generated by Django 5.2.16 on 2026-07-31 17:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0013_empresa_productos_con_imagen'),
        ('pedidos', '0011_detallepedidocomponente_alter_itemcarrito_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('proveedor', models.CharField(max_length=50)),
                ('identificador_externo', models.CharField(blank=True, max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('moneda', models.CharField(editable=False, max_length=3)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('url_pago', models.URLField(blank=True)),
                ('codigo_respuesta', models.CharField(blank=True, max_length=100)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='empresas.empresa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EventoWebhookPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=50)),
                ('evento_id', models.CharField(max_length=150)),
                ('referencia_pago', models.UUIDField()),
                ('estado_recibido', models.CharField(max_length=20)),
                ('hash_payload', models.CharField(editable=False, max_length=64)),
                ('procesado', models.BooleanField(default=False)),
                ('mensaje', models.CharField(blank=True, max_length=250)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_webhook', to='pagos.pago')),
            ],
            options={
                'verbose_name': 'evento webhook de pago',
                'verbose_name_plural': 'eventos webhook de pagos',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['empresa', 'estado'], name='pagos_pago_empresa_b70f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['proveedor', 'estado'], name='pagos_pago_proveed_3fe8fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('pedido',), name='pago_pendiente_unico_por_pedido'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('identificador_externo', ''), _negated=True), fields=('proveedor', 'identificador_externo'), name='pago_identificador_externo_unico'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='pago_monto_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='eventowebhookpago',
            constraint=models.UniqueConstraint(fields=('proveedor', 'evento_id'), name='evento_pago_unico_por_proveedor'),
        ),
    ]
