# Generated by Django 5.2.16 on 2026-08-06 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0016_empresa_facebook_url_empresa_instagram_url_and_more'),
        ('pagos', '0001_initial'),
        ('pedidos', '0012_alter_pedido_estado_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('en_linea', 'Pago en linea'), ('sucursal', 'Pago en sucursal')], default='en_linea', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['empresa', 'metodo', 'estado'], name='pagos_pago_empresa_32ac8c_idx'),
        ),
    ]
