# Generated by Django 5.2.16 on 2026-07-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='existencia_minima',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad minima para alertas internas de inventario bajo.'),
        ),
    ]
