# Generated by Django 5.2.16 on 2026-07-22 22:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_existencia_minima'),
        ('empresas', '0007_sucursalempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo/familias/'),
        ),
        migrations.AddField(
            model_name='familia',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL externa futura para almacenamiento en linea.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL externa futura para almacenamiento en linea.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='orden_destacado',
            field=models.PositiveIntegerField(default=0, help_text='Prioridad manual para productos mas vendidos o destacados.'),
        ),
        migrations.CreateModel(
            name='PaqueteCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('combo', 'Combo'), ('perfil', 'Perfil')], max_length=20)),
                ('codigo', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_normal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_paquete', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_descuento', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='catalogo/paquetes/')),
                ('imagen_url', models.URLField(blank=True, help_text='URL externa futura para almacenamiento en linea.')),
                ('destacado', models.BooleanField(default=False, help_text='Usado para mostrar combos destacados en inicio.')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes_catalogo', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'paquete de catalogo',
                'verbose_name_plural': 'paquetes de catalogo',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_productos', to='catalogo.paquetecatalogo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_paquetes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'producto de paquete',
                'verbose_name_plural': 'productos de paquete',
                'ordering': ['orden', 'producto__nombre'],
            },
        ),
        migrations.AddField(
            model_name='paquetecatalogo',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='paquetes_catalogo', through='catalogo.PaqueteProducto', to='catalogo.producto'),
        ),
        migrations.AddConstraint(
            model_name='paqueteproducto',
            constraint=models.UniqueConstraint(fields=('paquete', 'producto'), name='paquete_producto_unico'),
        ),
        migrations.AddIndex(
            model_name='paquetecatalogo',
            index=models.Index(fields=['empresa', 'tipo', 'activo', 'orden'], name='catalogo_pa_empresa_452570_idx'),
        ),
        migrations.AddIndex(
            model_name='paquetecatalogo',
            index=models.Index(fields=['empresa', 'tipo', 'destacado', 'activo', 'orden'], name='catalogo_pa_empresa_e6b707_idx'),
        ),
        migrations.AddConstraint(
            model_name='paquetecatalogo',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='paquete_catalogo_codigo_unico_por_empresa'),
        ),
    ]
