# Generated by Django 5.2.16 on 2026-07-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_tipo_item_y_codigo_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo/categorias/'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL externa futura para almacenamiento en linea.'),
        ),
    ]
