# Generated by Django 5.2.16 on 2026-08-03 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_categoria_imagen_categoria_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paqueteproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
