# Generated by Django 5.2.16 on 2026-07-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('retiro_en_local', 'Retiro en local'), ('envio_local', 'Envio local'), ('envio_nacional', 'Envio nacional')], default='retiro_en_local', max_length=30),
        ),
    ]
