# Generated by Django 5.2.16 on 2026-07-21 16:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_tiene_envios'),
        ('pedidos', '0002_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(choices=[('envio_local', 'Envio local'), ('envio_nacional', 'Envio nacional')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_entrega', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'tarifa de entrega',
                'verbose_name_plural': 'tarifas de entrega',
                'ordering': ['empresa__nombre', 'tipo_entrega'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'tipo_entrega'), name='tarifa_entrega_unica_por_empresa_tipo')],
            },
        ),
    ]
