# Generated by Django 5.2.16 on 2026-07-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='inventario_descontado',
            field=models.BooleanField(default=False),
        ),
    ]
