# Generated by Django 5.2.16 on 2026-07-21 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_inventario_descontado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('leyenda', models.CharField(default='Este documento corresponde a una prefactura y no representa una factura fiscal original.', max_length=180)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prefactura', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'prefactura',
                'verbose_name_plural': 'prefacturas',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
    ]
