# Generated by Django 5.2.16 on 2026-07-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_prefactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='departamento_entrega',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='municipio_entrega',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_recibe',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='pedido',
            name='referencia_entrega',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono_recibe',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
