# Generated by Django 5.2.16 on 2026-07-29 20:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def inicializar_totales_finales(apps, schema_editor):
    DetallePedido = apps.get_model("pedidos", "DetallePedido")
    DetallePedido.objects.update(
        precio_unitario_final=models.F("precio_unitario"),
        subtotal_final=models.F("subtotal"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_detallepedido_codigo_interno'),
        ('promociones', '0003_descuentoproducto_descuentopromocional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='descuento_promocional',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido', to='promociones.descuentopromocional'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='descuento_unitario',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='porcentaje_descuento',
            field=models.PositiveSmallIntegerField(default=0, editable=False, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='precio_unitario_final',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='promocion_codigo',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='promocion_titulo',
            field=models.CharField(blank=True, editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='subtotal_final',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.RunPython(
            inicializar_totales_finales,
            migrations.RunPython.noop,
        ),
    ]
