# Generated by Django 5.2.16 on 2026-07-30 15:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_detallepedido_descuento_promocional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='aplica_impuesto',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tasa_impuesto',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.15'), editable=False, max_digits=5),
        ),
    ]
