# Generated by Django 5.2.16 on 2026-07-30 22:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def completar_fotografia_articulos_existentes(apps, schema_editor):
    DetallePedido = apps.get_model("pedidos", "DetallePedido")
    detalles = list(DetallePedido.objects.all())
    for detalle in detalles:
        detalle.tipo_articulo = "producto"
        detalle.codigo_articulo = detalle.codigo_barra or detalle.codigo_interno
        detalle.nombre_articulo = detalle.nombre_producto

    if detalles:
        DetallePedido.objects.bulk_update(
            detalles,
            ["tipo_articulo", "codigo_articulo", "nombre_articulo"],
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_categoria_imagen_categoria_imagen_url'),
        ('pedidos', '0010_pedido_aplica_impuesto_pedido_tasa_impuesto'),
        ('promociones', '0003_descuentoproducto_descuentopromocional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedidoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(editable=False, max_length=80)),
                ('codigo_barra', models.CharField(blank=True, editable=False, max_length=80, null=True)),
                ('nombre_producto', models.CharField(editable=False, max_length=180)),
                ('cantidad_por_unidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'componente de detalle de pedido',
                'verbose_name_plural': 'componentes de detalles de pedido',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'ordering': ['id'], 'verbose_name': 'item de carrito', 'verbose_name_plural': 'items de carrito'},
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='codigo_articulo',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_articulo',
            field=models.CharField(blank=True, editable=False, max_length=180),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='catalogo.paquetecatalogo'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='tipo_articulo',
            field=models.CharField(default='producto', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_carrito', to='catalogo.paquetecatalogo'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_carrito', to='catalogo.producto'),
        ),
        migrations.RunPython(
            completar_fotografia_articulos_existentes,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paquete__isnull', True), ('producto__isnull', False)), models.Q(('paquete__isnull', False), ('producto__isnull', True)), _connector='OR'), name='detalle_pedido_un_solo_tipo_articulo'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.UniqueConstraint(fields=('carrito', 'paquete'), name='item_carrito_paquete_unico'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paquete__isnull', True), ('producto__isnull', False)), models.Q(('paquete__isnull', False), ('producto__isnull', True)), _connector='OR'), name='item_carrito_un_solo_tipo_articulo'),
        ),
        migrations.AddField(
            model_name='detallepedidocomponente',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='pedidos.detallepedido'),
        ),
        migrations.AddField(
            model_name='detallepedidocomponente',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes_pedido', to='catalogo.producto'),
        ),
        migrations.AddConstraint(
            model_name='detallepedidocomponente',
            constraint=models.UniqueConstraint(fields=('detalle', 'producto'), name='detalle_pedido_componente_unico'),
        ),
    ]
