# Generated by Django 5.2.16 on 2026-08-06 20:20

import django.db.models.deletion
import pedidos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0016_empresa_facebook_url_empresa_instagram_url_and_more'),
        ('pedidos', '0012_alter_pedido_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente de seleccion'), ('en_linea', 'Pago en linea'), ('sucursal', 'Pago en sucursal')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_pago_sucursal', to='empresas.sucursalempresa'),
        ),
        migrations.AddField(
            model_name='prefactura',
            name='correo_enviado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefactura',
            name='fecha_ultimo_intento_correo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefactura',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=pedidos.models.fecha_vencimiento_prefactura),
        ),
        migrations.AddField(
            model_name='prefactura',
            name='intentos_correo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prefactura',
            name='leyenda',
            field=models.CharField(default='PREFACTURA - NO ES COMPROBANTE FISCAL', max_length=180),
        ),
    ]
