# Generated by Django 5.2.16 on 2026-07-22 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_tiene_envios'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('subtitulo', models.TextField(blank=True)),
                ('texto_boton', models.CharField(blank=True, max_length=60)),
                ('url_boton', models.URLField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/banners/')),
                ('imagen_url', models.URLField(blank=True, help_text='URL externa futura para almacenamiento en linea.')),
                ('texto_alternativo', models.CharField(blank=True, max_length=180)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banners_promocionales', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'banner promocional',
                'verbose_name_plural': 'banners promocionales',
                'ordering': ['orden', '-fecha_creacion', '-id'],
                'indexes': [models.Index(fields=['empresa', 'activo', 'orden'], name='promociones_empresa_109162_idx'), models.Index(fields=['empresa', 'fecha_inicio', 'fecha_fin'], name='promociones_empresa_f408ba_idx')],
            },
        ),
    ]
