# Generated by Django 5.2.16 on 2026-07-23 16:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_familia_imagen_familia_imagen_url_and_more'),
        ('empresas', '0007_sucursalempresa'),
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpromocional',
            name='url_boton',
            field=models.CharField(blank=True, help_text='Ruta interna como /promociones/oferta-1 o URL externa.', max_length=240),
        ),
        migrations.CreateModel(
            name='OfertaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_ofertas', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'producto de oferta',
                'verbose_name_plural': 'productos de oferta',
                'ordering': ['orden', 'producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='OfertaPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('producto', 'Producto'), ('productos', 'Varios productos'), ('paquete', 'Combo o perfil')], max_length=20)),
                ('codigo', models.CharField(max_length=80)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_normal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_oferta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_descuento', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/ofertas/')),
                ('imagen_url', models.URLField(blank=True, help_text='URL externa futura para almacenamiento en linea.')),
                ('url_destino', models.CharField(blank=True, help_text='Ruta interna o URL externa para abrir el detalle de la oferta.', max_length=240)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas_promocionales', to='empresas.empresa')),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ofertas_promocionales', to='catalogo.paquetecatalogo')),
                ('productos', models.ManyToManyField(blank=True, related_name='ofertas_promocionales', through='promociones.OfertaProducto', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'oferta promocional',
                'verbose_name_plural': 'ofertas promocionales',
                'ordering': ['orden', '-fecha_creacion', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ofertaproducto',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_productos', to='promociones.ofertapromocional'),
        ),
        migrations.AddIndex(
            model_name='ofertapromocional',
            index=models.Index(fields=['empresa', 'tipo', 'activo', 'orden'], name='promociones_empresa_71b7d2_idx'),
        ),
        migrations.AddIndex(
            model_name='ofertapromocional',
            index=models.Index(fields=['empresa', 'fecha_inicio', 'fecha_fin'], name='promociones_empresa_66fd79_idx'),
        ),
        migrations.AddConstraint(
            model_name='ofertapromocional',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='oferta_promocional_codigo_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='ofertaproducto',
            constraint=models.UniqueConstraint(fields=('oferta', 'producto'), name='oferta_producto_unico'),
        ),
    ]
