# Generated by Django 5.2.16 on 2026-07-29 20:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_tipo_item_y_codigo_interno'),
        ('empresas', '0011_empresa_modo_inventario'),
        ('promociones', '0002_alter_bannerpromocional_url_boton_ofertaproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_descuentos', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'producto de descuento',
                'verbose_name_plural': 'productos de descuento',
                'ordering': ['producto__nombre', 'producto_id'],
            },
        ),
        migrations.CreateModel(
            name='DescuentoPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('alcance', models.CharField(choices=[('todos', 'Todos los articulos'), ('seleccionados', 'Articulos seleccionados'), ('individual', 'Un articulo')], max_length=20)),
                ('porcentaje', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descuentos_promocionales', to='empresas.empresa')),
                ('productos', models.ManyToManyField(blank=True, related_name='descuentos_promocionales', through='promociones.DescuentoProducto', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'descuento promocional',
                'verbose_name_plural': 'descuentos promocionales',
                'ordering': ['-porcentaje', '-fecha_creacion', '-id'],
            },
        ),
        migrations.AddField(
            model_name='descuentoproducto',
            name='descuento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_productos', to='promociones.descuentopromocional'),
        ),
        migrations.AddIndex(
            model_name='descuentopromocional',
            index=models.Index(fields=['empresa', 'activo', 'alcance'], name='promociones_empresa_a55b22_idx'),
        ),
        migrations.AddIndex(
            model_name='descuentopromocional',
            index=models.Index(fields=['empresa', 'fecha_inicio', 'fecha_fin'], name='promociones_empresa_6d787f_idx'),
        ),
        migrations.AddConstraint(
            model_name='descuentopromocional',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='descuento_codigo_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='descuentoproducto',
            constraint=models.UniqueConstraint(fields=('descuento', 'producto'), name='descuento_producto_unico'),
        ),
    ]
