# Generated by Django 5.2.16 on 2026-07-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('administrador_maestro', 'Administrador maestro'), ('administrador_empresa', 'Administrador de empresa'), ('gerente', 'Gerente'), ('comprador', 'Comprador')], default='comprador', max_length=30),
        ),
    ]
