# Generated by Django 5.2.16 on 2026-07-21 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfilusuario_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('tipo', models.CharField(choices=[('verificacion_correo', 'Verificacion de correo')], default='verificacion_correo', max_length=30)),
                ('usado', models.BooleanField(default=False)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_verificacion_correo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'codigo de verificacion de correo',
                'verbose_name_plural': 'codigos de verificacion de correo',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'tipo', 'usado'], name='usuarios_co_usuario_1ebb98_idx')],
            },
        ),
    ]
