# Generated by Django 5.2.16 on 2026-07-21 20:55

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_tiene_envios'),
        ('usuarios', '0003_codigoverificacioncorreo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='numero_identidad',
            field=models.CharField(blank=True, default='', help_text='Numero de identidad hondureno de 13 digitos.', max_length=13, validators=[django.core.validators.RegexValidator(message='El numero de identidad debe tener exactamente 13 digitos.', regex='^\\d{13}$')]),
        ),
        migrations.AddConstraint(
            model_name='perfilusuario',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False), models.Q(('numero_identidad', ''), _negated=True)), fields=('empresa', 'numero_identidad'), name='perfil_identidad_unica_por_empresa'),
        ),
    ]
