# Generated by Django 5.2.16 on 2026-07-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilusuario_numero_identidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoverificacioncorreo',
            name='tipo',
            field=models.CharField(choices=[('verificacion_correo', 'Verificacion de correo'), ('recuperacion_contrasena', 'Recuperacion de contrasena')], default='verificacion_correo', max_length=30),
        ),
    ]
