# Generated by Django 5.2.16 on 2026-08-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_empresa_productos_con_imagen'),
        ('usuarios', '0005_alter_codigoverificacioncorreo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='empresas_permitidas',
            field=models.ManyToManyField(blank=True, help_text='Empresas que puede administrar un administrador maestro. Los superusuarios no requieren esta asignacion.', related_name='administradores_maestros_permitidos', to='empresas.empresa'),
        ),
    ]
