# Generated by Django 5.2.16 on 2026-08-10 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfilusuario_empresas_permitidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='El telefono solo debe contener numeros.', regex='^\\d+$')]),
        ),
    ]
