# Generated by Django 5.2.16 on 2026-08-13 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0020_normalizar_orden_municipios'),
        ('usuarios', '0008_perfilusuario_municipio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='acepta_privacidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='acepta_promociones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='acepta_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_aceptacion_promociones',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_aceptacion_terminos_privacidad',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_retiro_promociones',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='version_privacidad_aceptada',
            field=models.CharField(blank=True, default='', editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='version_terminos_aceptada',
            field=models.CharField(blank=True, default='', editable=False, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='perfilusuario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('acepta_privacidad', False), ('acepta_terminos', False), ('fecha_aceptacion_terminos_privacidad__isnull', True), ('version_privacidad_aceptada', ''), ('version_terminos_aceptada', '')), models.Q(('acepta_privacidad', True), ('acepta_terminos', True), ('fecha_aceptacion_terminos_privacidad__isnull', False), models.Q(('version_terminos_aceptada', ''), _negated=True), models.Q(('version_privacidad_aceptada', ''), _negated=True)), _connector='OR'), name='perfil_aceptacion_legal_consistente'),
        ),
        migrations.AddConstraint(
            model_name='perfilusuario',
            constraint=models.CheckConstraint(condition=models.Q(('acepta_promociones', False), models.Q(('acepta_promociones', True), ('fecha_aceptacion_promociones__isnull', False), ('fecha_retiro_promociones__isnull', True)), _connector='OR'), name='perfil_promociones_aceptadas_consistente'),
        ),
    ]
