"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url
from decouple import config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def config_list(name, default=None):
    value = config(name) if default is None else config(name, default=default)
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", cast=bool)

ALLOWED_HOSTS = config_list("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = config_list("CSRF_TRUSTED_ORIGINS")
CORS_ALLOWED_ORIGINS = config_list("CORS_ALLOWED_ORIGINS")
CORS_ALLOWED_ORIGIN_REGEXES = config_list(
    "CORS_ALLOWED_ORIGIN_REGEXES",
    default="",
)
CORS_ALLOW_CREDENTIALS = config("CORS_ALLOW_CREDENTIALS", cast=bool)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'empresas.apps.EmpresasConfig',
    'usuarios.apps.UsuariosConfig',
    'catalogo.apps.CatalogoConfig',
    'inventario.apps.InventarioConfig',
    'pedidos.apps.PedidosConfig',
    'pagos.apps.PagosConfig',
    'favoritos.apps.FavoritosConfig',
    'promociones.apps.PromocionesConfig',
    'contacto.apps.ContactoConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'empresas.middleware.EmpresaContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = config("DATABASE_URL")

DATABASES = {
    'default': dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
    )
}

LEGACY_DATABASE_URL = config('LEGACY_DATABASE_URL', default='')
if LEGACY_DATABASE_URL:
    DATABASES['legacy'] = dj_database_url.parse(
        LEGACY_DATABASE_URL,
        conn_max_age=0,
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-hn'

TIME_ZONE = 'America/Tegucigalpa'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_DIR = BASE_DIR / 'static'
STATICFILES_DIRS = [STATIC_DIR] if STATIC_DIR.is_dir() else []

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
R2_STORAGE_ENABLED = config('R2_STORAGE_ENABLED', default=False, cast=bool)

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

if R2_STORAGE_ENABLED:
    r2_endpoint_url = config('R2_ENDPOINT_URL').rstrip('/')
    r2_public_base_url = config('R2_PUBLIC_BASE_URL').rstrip('/')
    r2_endpoint = urlparse(r2_endpoint_url)
    r2_public_base = urlparse(r2_public_base_url)

    if r2_endpoint.scheme != 'https' or not r2_endpoint.netloc:
        raise ImproperlyConfigured(
            'R2_ENDPOINT_URL debe ser una URL HTTPS completa.'
        )
    if (
        r2_public_base.scheme != 'https'
        or not r2_public_base.netloc
        or r2_public_base.path not in ('', '/')
    ):
        raise ImproperlyConfigured(
            'R2_PUBLIC_BASE_URL debe contener solo el dominio publico HTTPS.'
        )

    MEDIA_URL = f'{r2_public_base_url}/media/'
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'access_key': config('R2_ACCESS_KEY_ID'),
            'secret_key': config('R2_SECRET_ACCESS_KEY'),
            'bucket_name': config('R2_BUCKET_NAME'),
            'endpoint_url': r2_endpoint_url,
            'region_name': config('R2_REGION_NAME', default='auto'),
            'custom_domain': r2_public_base.netloc,
            'url_protocol': 'https:',
            'location': 'media',
            'default_acl': None,
            'querystring_auth': False,
            'file_overwrite': False,
        },
    }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=config('JWT_ACCESS_TOKEN_MINUTES', cast=int)
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        hours=config('JWT_SESSION_MAX_HOURS', cast=int)
    ),
    'ROTATE_REFRESH_TOKENS': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

JWT_SESSION_MAX_SECONDS = int(
    SIMPLE_JWT['REFRESH_TOKEN_LIFETIME'].total_seconds()
)
JWT_REFRESH_COOKIE_NAME = config(
    'JWT_REFRESH_COOKIE_NAME',
)
JWT_REFRESH_COOKIE_SECURE = config(
    'JWT_REFRESH_COOKIE_SECURE',
    cast=bool,
)
JWT_REFRESH_COOKIE_SAMESITE = config(
    'JWT_REFRESH_COOKIE_SAMESITE',
)
JWT_REFRESH_COOKIE_PATH = '/api/'

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
)
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
)

PAGOS_PROVEEDOR_DEFAULT = config(
    'PAGOS_PROVEEDOR_DEFAULT',
)
PAGOS_WEBHOOK_SECRET = config(
    'PAGOS_WEBHOOK_SECRET',
    default='',
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
