# Generated by Django 5.2.16 on 2026-07-30 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_categoria_imagen_categoria_imagen_url'),
        ('empresas', '0013_empresa_productos_con_imagen'),
        ('favoritos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='favoritos', to='catalogo.paquetecatalogo'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='favoritos', to='catalogo.producto'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('empresa', 'usuario', 'paquete'), name='favorito_unico_por_empresa_usuario_paquete'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paquete__isnull', True), ('producto__isnull', False)), models.Q(('paquete__isnull', False), ('producto__isnull', True)), _connector='OR'), name='favorito_un_solo_tipo_articulo'),
        ),
    ]
