# Generated by Django 5.2.16 on 2026-07-10 22:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('color_principal', models.CharField(default='#d1393d', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe tener formato hexadecimal, por ejemplo #d1393d.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_secundario', models.CharField(default='#e94a51', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe tener formato hexadecimal, por ejemplo #d1393d.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_acento', models.CharField(default='#2d4b77', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe tener formato hexadecimal, por ejemplo #d1393d.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_texto', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe tener formato hexadecimal, por ejemplo #d1393d.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_fondo', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe tener formato hexadecimal, por ejemplo #d1393d.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('sitio_web', models.URLField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['nombre'],
            },
        ),
    ]
