# Generated by Django 5.2.16 on 2026-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tiene_envios',
            field=models.BooleanField(default=False, help_text='Si esta activo, la empresa podra ofrecer envio local y envio nacional.'),
        ),
    ]
