# Generated by Django 5.2.16 on 2026-07-22 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_tiene_envios'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dominio_personalizado',
            field=models.CharField(blank=True, help_text='Ejemplo: tienda.analizahn.com. No incluir http ni puerto.', max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Escribe solo el dominio, por ejemplo analiza.localhost o tienda.analizahn.com.', regex='^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$')]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='subdominio',
            field=models.CharField(blank=True, help_text='Ejemplo: analiza para abrir analiza.localhost o analiza.tuapp.com.', max_length=63, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El subdominio solo puede usar letras minusculas, numeros y guiones.', regex='^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$')]),
        ),
    ]
