# Generated by Django 5.2.16 on 2026-07-22 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_poblar_subdominios_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMenuEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(help_text='Identificador estable, por ejemplo inicio, catalogo o contacto.', max_length=60)),
                ('texto', models.CharField(max_length=80)),
                ('ruta', models.CharField(help_text='Ruta del frontend, por ejemplo /examenes o una URL externa.', max_length=180)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('abre_en_nueva_pestana', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_menu', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'item de menu de empresa',
                'verbose_name_plural': 'items de menu de empresa',
                'ordering': ['empresa__nombre', 'orden', 'texto'],
                'indexes': [models.Index(fields=['empresa', 'activo', 'orden'], name='empresas_it_empresa_45c138_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'clave'), name='item_menu_clave_unica_por_empresa')],
            },
        ),
    ]
