# Generated by Django 5.2.16 on 2026-07-22 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_poblar_menu_empresas_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('horario', models.CharField(blank=True, max_length=180)),
                ('google_maps_url', models.URLField(blank=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'sucursal de empresa',
                'verbose_name_plural': 'sucursales de empresa',
                'ordering': ['empresa__nombre', 'orden', 'nombre'],
                'indexes': [models.Index(fields=['empresa', 'activa', 'orden'], name='empresas_su_empresa_e5fb9f_idx')],
            },
        ),
    ]
