# Generated by Django 5.2.16 on 2026-07-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_sucursalempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursalempresa',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sucursalempresa',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
