# Generated by Django 5.2.16 on 2026-07-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_alter_sucursalempresa_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursalempresa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/sucursales/'),
        ),
        migrations.AddField(
            model_name='sucursalempresa',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL externa futura para almacenamiento en linea.'),
        ),
    ]
