# Generated by Django 5.2.16 on 2026-07-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_sucursalempresa_imagen_sucursalempresa_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagen_sucursales',
            field=models.ImageField(blank=True, help_text='Imagen general que usaran todas las sucursales de esta empresa.', null=True, upload_to='empresas/sucursales/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_sucursales_url',
            field=models.URLField(blank=True, help_text='URL externa futura para la imagen general de sucursales.'),
        ),
    ]
