# Generated by Django 5.2.16 on 2026-07-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_empresa_modo_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cobra_impuesto',
            field=models.BooleanField(default=True, help_text='Si esta activo, las ventas calcularan el 15% de ISV.'),
        ),
    ]
