# Generated by Django 5.2.16 on 2026-07-30 17:44

from django.db import migrations, models


def desactivar_imagenes_productos_analiza(apps, schema_editor):
    Empresa = apps.get_model("empresas", "Empresa")
    Empresa.objects.filter(slug__iexact="Analiza").update(
        productos_con_imagen=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_empresa_cobra_impuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='productos_con_imagen',
            field=models.BooleanField(default=True, help_text='Si esta activo, los productos pueden mostrar imagenes individuales. Si esta desactivado, se usan imagenes de familias y categorias.'),
        ),
        migrations.RunPython(
            desactivar_imagenes_productos_analiza,
            migrations.RunPython.noop,
        ),
    ]
