# Generated by Django 5.2.16 on 2026-08-03 16:54

import django.db.models.deletion
from django.db import migrations, models


MENU_OFICIAL = [
    ("inicio", "Inicio", "/", 1),
    ("examenes", "Examenes", "/examenes", 2),
    ("perfiles", "Perfiles", "/perfiles", 3),
    ("servicios", "Servicios", "/servicios", 4),
    ("promociones", "Promociones", "/promociones", 5),
    ("sucursales", "Sucursales", "/sucursales", 6),
    ("contacto", "Contacto", "/contacto", 7),
    ("sobre_nosotros", "Sobre nosotros", "/sobre-nosotros", 8),
]


def preparar_modulos_y_contenido(apps, schema_editor):
    Empresa = apps.get_model("empresas", "Empresa")
    ItemMenuEmpresa = apps.get_model("empresas", "ItemMenuEmpresa")
    SobreNosotrosEmpresa = apps.get_model("empresas", "SobreNosotrosEmpresa")
    claves_oficiales = {clave for clave, _texto, _ruta, _orden in MENU_OFICIAL}

    for empresa in Empresa.objects.all().iterator():
        items = list(ItemMenuEmpresa.objects.filter(empresa=empresa).order_by("id"))
        candidato_sobre_nosotros = next(
            (
                item
                for item in items
                if item.clave.lower().replace("-", "_") == "sobre_nosotros"
                or item.ruta.strip().lower() in ["/sobrenosotros", "/sobre-nosotros"]
            ),
            None,
        )
        oficial_sobre_nosotros = next(
            (item for item in items if item.clave == "sobre_nosotros"),
            None,
        )

        if candidato_sobre_nosotros and candidato_sobre_nosotros != oficial_sobre_nosotros:
            if oficial_sobre_nosotros:
                ItemMenuEmpresa.objects.filter(pk=oficial_sobre_nosotros.pk).update(
                    texto=candidato_sobre_nosotros.texto or "Sobre nosotros",
                    orden=candidato_sobre_nosotros.orden or 8,
                    activo=candidato_sobre_nosotros.activo,
                    ruta="/sobre-nosotros",
                    abre_en_nueva_pestana=False,
                )
                candidato_sobre_nosotros.delete()
            else:
                ItemMenuEmpresa.objects.filter(pk=candidato_sobre_nosotros.pk).update(
                    clave="sobre_nosotros",
                    ruta="/sobre-nosotros",
                    abre_en_nueva_pestana=False,
                )

        for clave, texto, ruta, orden in MENU_OFICIAL:
            item, creado = ItemMenuEmpresa.objects.get_or_create(
                empresa=empresa,
                clave=clave,
                defaults={
                    "texto": texto,
                    "ruta": ruta,
                    "orden": orden,
                    "activo": True,
                    "abre_en_nueva_pestana": False,
                },
            )
            if not creado:
                ItemMenuEmpresa.objects.filter(pk=item.pk).update(
                    ruta=ruta,
                    abre_en_nueva_pestana=False,
                )

        ItemMenuEmpresa.objects.filter(empresa=empresa).exclude(
            clave__in=claves_oficiales
        ).delete()
        SobreNosotrosEmpresa.objects.get_or_create(empresa=empresa)


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_empresa_productos_con_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreNosotrosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sobre nosotros', max_length=180)),
                ('introduccion', models.TextField(blank=True)),
                ('historia', models.TextField(blank=True)),
                ('mision', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('valores', models.TextField(blank=True, help_text='Escribe un valor por linea.')),
                ('compromiso', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresas/sobre_nosotros/')),
                ('imagen_url', models.URLField(blank=True, help_text='URL externa futura para almacenamiento en linea.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'contenido de Sobre nosotros',
                'verbose_name_plural': 'contenidos de Sobre nosotros',
            },
        ),
        migrations.AlterField(
            model_name='itemmenuempresa',
            name='clave',
            field=models.SlugField(choices=[('inicio', 'Inicio'), ('examenes', 'Examenes'), ('perfiles', 'Perfiles'), ('servicios', 'Servicios'), ('promociones', 'Promociones'), ('sucursales', 'Sucursales'), ('contacto', 'Contacto'), ('sobre_nosotros', 'Sobre nosotros')], help_text='Modulo oficial del sistema. No puede cambiarse despues de crearlo.', max_length=60),
        ),
        migrations.AddField(
            model_name='sobrenosotrosempresa',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sobre_nosotros', to='empresas.empresa'),
        ),
        migrations.RunPython(
            preparar_modulos_y_contenido,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='itemmenuempresa',
            constraint=models.CheckConstraint(condition=models.Q(('clave__in', ('inicio', 'examenes', 'perfiles', 'servicios', 'promociones', 'sucursales', 'contacto', 'sobre_nosotros'))), name='item_menu_clave_oficial'),
        ),
    ]
