# Generated by Django 5.2.16 on 2026-08-03 17:39

import empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0015_normalizar_orden_menu_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, validators=[empresas.models.validar_url_facebook]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, validators=[empresas.models.validar_url_instagram]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=500, validators=[empresas.models.validar_url_tiktok]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='Ejemplo: https://wa.me/50499999999', max_length=500, validators=[empresas.models.validar_url_whatsapp]),
        ),
    ]
